// Courses data

export const courses = [
  {
    img: "https://img-c.udemycdn.com/course/750x422/2492962_f098.jpg",
    title: "Web Development Course",
    rating: 4.9,
    language: "Hindi",
    lectures: "50+",
    price: 15,
    isInCart: false,
  },
  {
    img: "https://img-c.udemycdn.com/course/480x270/1362070_b9a1_2.jpg",
    title: "Beginner Course | Reactjs",
    rating: 4.8,
    language: "English",
    lectures: "30+",
    price: 10,
    isInCart: false,
  },
  {
    img: "https://img-c.udemycdn.com/course/750x422/3713170_4a61_2.jpg",
    title: "Mern Stack Course",
    rating: 4.9,
    language: "English",
    lectures: "70+",
    price: 25,
    isInCart: false,
  },
  {
    img: "https://img-c.udemycdn.com/course/750x422/3502634_b2fd_3.jpg",
    title: "Java Programming Course",
    rating: 4.7,
    language: "Hindi",
    lectures: "30+",
    price: 15,
    isInCart: false,
  },
  {
    img: "https://img-c.udemycdn.com/course/750x422/3502634_b2fd_3.jpg",
    title: "DSA in C++ | Learn C++ also",
    rating: 4.9,
    language: "English",
    lectures: "60+",
    price: 30,
    isInCart: false,
  },
  {
    img: "https://img-c.udemycdn.com/course/750x422/2311010_7f4c_2.jpg",
    title: "Android Development Course",
    rating: 4.9,
    language: "Hindi",
    lectures: "30+",
    price: 20,
    isInCart: false,
  },
];
